"""Frozen public call-signature metadata for the v3 compatibility boundary."""

PUBLIC_EXCEPTION_EXPORTS = {
    "BOForgeError",
    "ConfigError",
    "LogBusyError",
    "LogConflictError",
    "LogValidationError",
    "LogWriteError",
    "ProvenanceError",
    "SuggestionError",
}

PUBLIC_SIGNATURE_NAMES = {
    "BOConfig",
    "CampaignConfig",
    "CampaignSession",
    "ConstraintConfig",
    "ContextConfig",
    "CostConfig",
    "FidelityConfig",
    "ModelConfig",
    "ObjectiveConfig",
    "ReplicateConfig",
    "ReviewConfig",
    "StageConfig",
    "VariableConfig",
    "active_variables_for_stage",
    "aggregate_observed_replicates",
    "append_suggestions",
    "best_replicate_group",
    "configured_stage_names",
    "context_summary",
    "evaluate_cost",
    "fidelity_coverage",
    "fidelity_summary",
    "get_observed_data",
    "hypervolume",
    "hypervolume_progress",
    "is_structured_campaign",
    "load_campaign_log",
    "mark_observed",
    "model_profile_comparison",
    "model_summary",
    "pareto_front",
    "pareto_summary",
    "provenance_summary",
    "qlog_nei_summary",
    "replicate_summary",
    "review_suggestion",
    "stage_summary",
    "suggest_next",
    "suggestion_quality_summary",
    "validate_campaign_data",
}

SESSION_METHOD_NAMES = {
    "append_suggestions",
    "best_observation",
    "best_replicate_group",
    "campaign_status",
    "context_summary",
    "cost_summary",
    "export_report",
    "fidelity_coverage",
    "fidelity_summary",
    "from_files",
    "initialize",
    "mark_observed",
    "model_profile_comparison",
    "model_summary",
    "next_action",
    "observed_data",
    "pareto_front",
    "pareto_summary",
    "pending_suggestions",
    "plot_context_diagnostics",
    "plot_cost_progress",
    "plot_diagnostics",
    "plot_fidelity_diagnostics",
    "plot_fidelity_progress",
    "plot_hypervolume",
    "plot_model_comparison",
    "plot_model_diagnostics",
    "plot_pareto",
    "plot_pareto_parallel",
    "plot_progress",
    "plot_qlog_nei_diagnostics",
    "plot_replicates",
    "plot_stage_diagnostics",
    "qlog_nei_summary",
    "provenance_summary",
    "reload",
    "replicate_summary",
    "report",
    "review_queue",
    "review_suggestion",
    "stage_summary",
    "suggest_next",
    "suggestion_quality",
    "summary",
    "validate",
}

# Hashes cover the complete name-to-signature maps. Failed assertions print the maps.
PUBLIC_SIGNATURE_DIGEST = "5513764474dbcf3797ec6b135263d1a703e854f66b5aaf4f8d13113a0c349fd3"
SESSION_METHOD_SIGNATURE_DIGEST = (
    "b041e46ef119c488e88f97ef3db9b38b1af446617431a96fa34d2a170ec18e8a"
)
