"""Frozen public call-signature metadata for the v3 compatibility boundary."""

PUBLIC_EXCEPTION_EXPORTS = {
    "BOForgeError",
    "ConfigError",
    "LogBusyError",
    "LogConflictError",
    "LogValidationError",
    "LogWriteError",
    "SuggestionError",
}

PUBLIC_SIGNATURE_NAMES = {
    "BOConfig",
    "CampaignConfig",
    "CampaignSession",
    "ConstraintConfig",
    "ContextConfig",
    "CostConfig",
    "FidelityConfig",
    "ModelConfig",
    "ObjectiveConfig",
    "ReplicateConfig",
    "ReviewConfig",
    "StageConfig",
    "VariableConfig",
    "active_variables_for_stage",
    "aggregate_observed_replicates",
    "append_suggestions",
    "best_replicate_group",
    "configured_stage_names",
    "context_summary",
    "evaluate_cost",
    "fidelity_coverage",
    "fidelity_summary",
    "get_observed_data",
    "hypervolume",
    "hypervolume_progress",
    "is_structured_campaign",
    "load_campaign_log",
    "mark_observed",
    "model_profile_comparison",
    "model_summary",
    "pareto_front",
    "pareto_summary",
    "qlog_nei_summary",
    "replicate_summary",
    "review_suggestion",
    "stage_summary",
    "suggest_next",
    "suggestion_quality_summary",
    "validate_campaign_data",
}

SESSION_METHOD_NAMES = {
    "append_suggestions",
    "best_observation",
    "best_replicate_group",
    "campaign_status",
    "context_summary",
    "cost_summary",
    "export_report",
    "fidelity_coverage",
    "fidelity_summary",
    "from_files",
    "mark_observed",
    "model_profile_comparison",
    "model_summary",
    "next_action",
    "observed_data",
    "pareto_front",
    "pareto_summary",
    "pending_suggestions",
    "plot_context_diagnostics",
    "plot_cost_progress",
    "plot_diagnostics",
    "plot_fidelity_diagnostics",
    "plot_fidelity_progress",
    "plot_hypervolume",
    "plot_model_comparison",
    "plot_model_diagnostics",
    "plot_pareto",
    "plot_pareto_parallel",
    "plot_progress",
    "plot_qlog_nei_diagnostics",
    "plot_replicates",
    "plot_stage_diagnostics",
    "qlog_nei_summary",
    "reload",
    "replicate_summary",
    "report",
    "review_queue",
    "review_suggestion",
    "stage_summary",
    "suggest_next",
    "suggestion_quality",
    "summary",
    "validate",
}

# Hashes cover the complete name-to-signature maps. Failed assertions print the maps.
PUBLIC_SIGNATURE_DIGEST = "658ec570dad2712da3eb2d9646be832bba251853badf961c47a5db859962cb4b"
SESSION_METHOD_SIGNATURE_DIGEST = (
    "84784177ebf6096a3c02ed2a9da0c22c74e6b71ca00815638c275bb28e5c6feb"
)
