"""Release-neutral CI, packaging, and publication-assurance contracts."""

from __future__ import annotations

import re
import tomllib
from pathlib import Path

import yaml

import bo_forge

PROJECT_ROOT = Path(__file__).resolve().parents[1]
PROJECT_METADATA = tomllib.loads(
    (PROJECT_ROOT / "pyproject.toml").read_text(encoding="utf-8")
)["project"]
PROJECT_VERSION = PROJECT_METADATA["version"]
CONSTRAINT_FILES = (
    "constraints-py311-linux-x86_64.txt",
    "constraints-py312-linux-x86_64.txt",
    "constraints-py312-macos-arm64.txt",
    "constraints-py312-macos-x86_64.txt",
)


def _read(relative_path: str) -> str:
    return (PROJECT_ROOT / relative_path).read_text(encoding="utf-8")


def _workflow(relative_path: str) -> dict[str, object]:
    return yaml.load(_read(relative_path), Loader=yaml.BaseLoader)


def test_release_identity_and_maturity_are_aligned() -> None:
    assert re.fullmatch(r"\d+\.\d+\.\d+", PROJECT_VERSION)
    assert bo_forge.__version__ == PROJECT_VERSION
    assert "Development Status :: 4 - Beta" in PROJECT_METADATA["classifiers"]
    assert "Development Status :: 5 - Production/Stable" not in PROJECT_METADATA[
        "classifiers"
    ]
    assert f'__version__ = "{PROJECT_VERSION}"' in _read("bo_forge/__init__.py")
    assert f"# 🧪 BO Forge v{PROJECT_VERSION}" in _read("README.md")
    current_changelog_heading = next(
        line for line in _read("CHANGELOG.md").splitlines() if line.startswith("## v")
    )
    assert current_changelog_heading.startswith(f"## v{PROJECT_VERSION} - ")


def test_generated_constraints_are_hashed_and_resolver_pinned() -> None:
    requirements_dir = PROJECT_ROOT / "requirements"

    assert not (PROJECT_ROOT / "requirements-lock.txt").exists()
    generated = tuple(sorted(path.name for path in requirements_dir.glob("constraints-*.txt")))
    assert generated == CONSTRAINT_FILES
    for filename in CONSTRAINT_FILES:
        content = (requirements_dir / filename).read_text(encoding="utf-8")
        assert content.startswith("# This file was autogenerated by uv")
        assert "uv==0.11.3 pip compile pyproject.toml" in content.splitlines()[1]
        assert "--generate-hashes" in content.splitlines()[1]
        assert content.count("==") > 50
        assert content.count("--hash=sha256:") > 50

    for filename in CONSTRAINT_FILES[:2]:
        content = (requirements_dir / filename).read_text(encoding="utf-8")
        assert "--torch-backend cpu" in content.splitlines()[1]
        assert re.search(r"(?m)^torch==[^\s]+\+cpu \\\s*$", content)


def test_required_ci_covers_supported_platforms_and_artifacts() -> None:
    workflow = _read(".github/workflows/ci.yml")
    workflow_data = _workflow(".github/workflows/ci.yml")

    required_fragments = (
        "permissions:\n  contents: read",
        'python: "3.11"',
        'python: "3.12"',
        "runs-on: macos-14",
        "python -m pytest -p no:cacheprovider",
        "ruff check . --no-cache",
        "Verify generated constraints",
        "Path, lock, rollback, and mutation tests",
        "Bounded real numerical paths",
        "python -m build --outdir",
        "python -m twine check",
        "_assert_wheel_package_boundaries",
        "_assert_sdist_contains_release_assets",
        "python -m pip check",
        "bo-forge-app",
        "bo-forge-api",
        "from bo_forge_api.api import create_app",
        'assert not hasattr(bo_forge_api, "create_app")',
        '"${wheel}[app]"',
        '"${wheel}[api]"',
        'assert importlib.util.find_spec("streamlit") is None',
        'assert importlib.util.find_spec("fastapi") is None',
    )
    for fragment in required_fragments:
        assert fragment in workflow

    assert "pull_request_target" not in workflow
    assert "from bo_forge_api import create_app" not in workflow
    assert '"${wheel}[app,api]"' not in workflow
    assert "0.0.0.0" not in workflow
    assert "-print -quit" not in workflow
    jobs = workflow_data["jobs"]
    assert set(jobs) == {
        "static",
        "core-tests",
        "macos-filesystem",
        "numerical",
        "package",
    }
    assert all(int(job["timeout-minutes"]) > 0 for job in jobs.values())


def test_provenance_filesystem_acceptance_is_in_macos_ci_and_checklist() -> None:
    workflow = _workflow(".github/workflows/ci.yml")
    steps = workflow["jobs"]["macos-filesystem"]["steps"]
    command = next(step["run"] for step in steps if step.get("name") ==
                   "Path, lock, rollback, and mutation tests")
    for name in ("test_provenance.py", "test_provenance_resume.py",
                 "test_provenance_lifecycle.py", "test_provenance_lifecycle_hardening.py",
                 "test_provenance_acceptance.py", "test_provenance_closeout.py"):
        assert f"tests/{name}" in command
        assert f"tests/{name}" in _read("docs/RELEASE_CHECKLIST.md")


def test_predictive_publication_and_snapshot_checks_run_on_linux_and_macos() -> None:
    workflow = _workflow(".github/workflows/ci.yml")
    linux = workflow["jobs"]["core-tests"]
    assert linux["runs-on"] == "ubuntu-latest"
    assert any(step.get("run") == "python -m pytest -p no:cacheprovider" for step in linux["steps"])
    steps = workflow["jobs"]["macos-filesystem"]["steps"]
    command = next(step["run"] for step in steps if step.get("name") ==
                   "Path, lock, rollback, and mutation tests")
    for name in ("test_predictive_exports.py", "test_predictive_hardening.py"):
        assert f"tests/{name}" in command
        assert f"tests/{name}" in _read("docs/RELEASE_CHECKLIST.md")


def test_beginner_setup_contract_and_links() -> None:
    guide = _read("START_HERE.md")
    assert re.findall(r"^## (\d+)\.", guide, re.M) == [str(i) for i in range(1, 11)]
    for command in ('python3.12 -m venv .venv', 'source .venv/bin/activate',
                    'python -m pip install ".[app]"', 'python -m pip check',
                    'python -m bo_forge --version', 'python -m bo_forge doctor',
                    'python -m bo_forge_app', 'python -m bo_forge_app --port 8502'):
        assert command in guide
    assert f"bo-forge {PROJECT_VERSION}" in guide
    assert "Nothing loaded yet." in guide
    assert "After you load or create a campaign" in guide
    for text in ("Code > Download ZIP", "pyproject.toml", "Ctrl+C", "Command Prompt",
                 "Windows is not in the tested platform matrix", "Campaign", "Run", "Analyze",
                 "http://127.0.0.1:8501", "http://127.0.0.1:8502"):
        assert text in guide
    for forbidden in ("sudo pip", "--break-system-packages", "--trusted-host",
                      "--allow-network-access", 'pip install "bo-forge[app]"'):
        assert forbidden not in guide
    for target in re.findall(r"\]\(([^)]+)\)", guide):
        if not target.startswith("https://"):
            assert (PROJECT_ROOT / target).is_file(), target
    for name in ("README.md", "docs/INSTALLATION.md", "docs/STREAMLIT_APP.md"):
        assert "START_HERE.md" in _read(name)
    assert "include START_HERE.md" in _read("MANIFEST.in")
    tutorial = _read("docs/09_APP_CREATED_CAMPAIGN_TUTORIAL.md")
    assert "both files" not in tutorial
    assert "campaign_log.csv.manifest.json" in tutorial


def test_future_tag_gate_validates_without_publishing() -> None:
    workflow = _read(".github/workflows/release-gate.yml")
    workflow_data = _workflow(".github/workflows/release-gate.yml")

    for fragment in (
        "tags: [\"v*\"]",
        "Tag {tag} does not match package version {version}",
        "Checked-out commit is not exactly tagged {tag}",
        "python -m pytest -p no:cacheprovider",
        "ruff check . --no-cache",
        "python -m build --outdir",
        "python -m twine check",
        "from bo_forge_api.api import create_app",
        'assert not hasattr(bo_forge_api, "create_app")',
        '"${wheel}[app]"',
        '"${wheel}[api]"',
        '"$sdist"',
        'assert importlib.util.find_spec("streamlit") is None',
        'assert importlib.util.find_spec("fastapi") is None',
        "actions/upload-artifact@v4",
        "retention-days: 14",
    ):
        assert fragment in workflow

    forbidden = (
        "pull_request_target",
        "twine upload",
        "gh release",
        "pypa/gh-action-pypi-publish",
        "softprops/action-gh-release",
        "id-token: write",
    )
    for fragment in forbidden:
        assert fragment not in workflow
    assert "from bo_forge_api import create_app" not in workflow
    assert '"${wheel}[app,api]"' not in workflow
    assert "-print -quit" not in workflow
    assert set(workflow_data["jobs"]) == {"validate-tag"}
    assert int(workflow_data["jobs"]["validate-tag"]["timeout-minutes"]) > 0


def test_release_facing_files_do_not_expose_author_home_paths() -> None:
    candidates = [
        PROJECT_ROOT / "README.md",
        PROJECT_ROOT / "CHANGELOG.md",
        PROJECT_ROOT / "CONTRIBUTING.md",
        PROJECT_ROOT / "SECURITY.md",
        PROJECT_ROOT / "MANIFEST.in",
        PROJECT_ROOT / "pyproject.toml",
        *PROJECT_ROOT.glob("ROADMAP*.md"),
        *PROJECT_ROOT.glob("docs/**/*.md"),
        *PROJECT_ROOT.glob("examples/**/*.py"),
        *PROJECT_ROOT.glob("notebooks/**/*.ipynb"),
    ]
    posix_home = re.compile(
        r"/(?:Users|home)/(?!USER(?:/|$)|user(?:/|$)|username(?:/|$)|"
        r"yourname(?:/|$)|<)[^/\s`\"']+/"
    )
    windows_home = re.compile(
        r"[A-Za-z]:\\Users\\(?!USER\\|user\\|username\\|yourname\\|<)"
        r"[^\\\s`\"']+\\"
    )

    offenders = []
    for path in candidates:
        content = path.read_text(encoding="utf-8")
        if posix_home.search(content) or windows_home.search(content):
            offenders.append(path.relative_to(PROJECT_ROOT).as_posix())

    assert offenders == []


def test_contribution_security_and_release_guidance_define_boundaries() -> None:
    contributing = _read("CONTRIBUTING.md")
    security = _read("SECURITY.md")
    release = _read("docs/RELEASE_CHECKLIST.md")

    assert "generated development constraints live in `requirements/`" in contributing
    assert "Do not hand-edit generated constraints" in contributing
    assert "private vulnerability reporting flow" in security.lower()
    assert "This file does not enable or" in security
    assert "verify that repository setting" in security
    assert "exact release commit is the authoritative gate" in release
    assert "Creating a tag, GitHub Release" in release
    assert "separate explicit authorization" in release


def test_release_checklist_uses_isolated_optional_extra_probes() -> None:
    release = _read("docs/RELEASE_CHECKLIST.md")

    assert "/tmp/bo-forge-app-probe/bin/bo-forge-app --help" in release
    assert "/tmp/bo-forge-api-probe/bin/bo-forge-api --help" in release
    assert '"${wheel}[app]"' in release
    assert '"${wheel}[api]"' in release
    assert "from bo_forge_api.api import create_app" in release
    assert 'assert not hasattr(bo_forge_api, "create_app")' in release
    assert "/tmp/bo-forge-wheel-probe/bin/bo-forge-app" not in release
    assert "/tmp/bo-forge-wheel-probe/bin/bo-forge-api" not in release


def test_v3_roadmap_records_assurance_and_future_findings() -> None:
    roadmap = _read("ROADMAP_V3_X.md")

    for node in ("v301", "v302", "v310", "v311", "v320", "v330", "v340", "v344"):
        assert f'{node}["' in roadmap
    for finding in ("REL-001", "REP-001", "REP-002", "DOC-001", "DOC-002", "DX-001"):
        assert finding in roadmap
    assert f"Current prepared baseline: `v{PROJECT_VERSION}`" in roadmap
    assert "Status: prepared; publication requires separate authorization" in roadmap
    assert f"### v{PROJECT_VERSION} - " in roadmap
    assert "class v30,v31 majorDone" in roadmap
    assert "class v310,v311,v312,v313 patchDone" in roadmap
    assert "class v313 patchActive" not in roadmap
    assert "class v32 majorActive" in roadmap
    assert "class v320,v321 patchDone" in roadmap
    assert "| `v3.2.0` | prepared | Complete foundation:" in roadmap
    assert "| `v3.2.1` | prepared | Atomic exports," in roadmap
    for version in ("3.2.2", "3.2.3"):
        assert f"| `v{version}` | planned |" in roadmap
    assert "### v3.2.1 - Diagnostics Hardening" in roadmap
    assert "### v3.2.2 - Interpretation And Calibration Guidance" in roadmap
    assert "### v3.2.3 - Synthetic Acceptance And Interpretation Contract" in roadmap
    assert (
        "### v3.1.3 - Provenance Acceptance And Beginner Setup\n\n"
        "Status: implementation complete; publication requires separate authorization "
        "and exact-commit CI"
    ) in roadmap
    checklist = _read("docs/RELEASE_CHECKLIST.md")
    assert "CI on that exact commit" in checklist
    assert "Implementation completion does not grant publication approval." in checklist
    assert "## v3.0.x - Architecture And Release Assurance\n\nStatus: completed" in roadmap
    assert "## v3.1.x - Durable Campaign Provenance\n\nStatus: completed" in roadmap
    assert "No tag, GitHub Release, package publication, or push occurs" in roadmap


def test_predictive_foundation_docs_preserve_scope_and_interpretation() -> None:
    for path in (
        "README.md", "docs/PUBLIC_API.md", "docs/CLI.md",
        "docs/STREAMLIT_APP.md", "docs/CAPABILITY_MATRIX.md",
    ):
        content = _read(path)
        for fragment in (
            "evaluation_scope=in_sample", "5..200", "2..5",
            "duplicate designs", "observation noise", "original objective units",
        ):
            assert fragment in content, (path, fragment)
    public_api = _read("docs/PUBLIC_API.md")
    for fragment in (
        "FitMetadata", "frozen record", "metadata=None", "no ambient fit history",
        "PredictiveEvaluationResult", "model_predictive_evaluation",
        "new destination directory", "summary.csv", "predictions.csv",
        "fold_outcomes.csv", "metadata.json", "rmse", "mae", "mean_nlpd",
        "interval_coverage", "mean_interval_width", "incomplete",
        "result.plot_predictions(save_path=None)", "result.plot_residuals(save_path=None)",
    ):
        assert fragment in public_api
    for option in ("model-evaluate", "--profile", "--folds", "--seed", "--output-dir"):
        assert option in _read("docs/CLI.md")
    for path in ("README.md", "docs/PUBLIC_API.md", "docs/CLI.md", "docs/RELEASE_CHECKLIST.md"):
        assert "notebooks/23_predictive_diagnostics.ipynb" in _read(path)


def test_predictive_hardening_docs_describe_exports_failures_and_snapshots() -> None:
    for path in ("docs/PREDICTIVE_EVALUATION.md", "docs/PUBLIC_API.md", "docs/CLI.md"):
        content = _read(path)
        for fragment in ("fit_message", "temporary sibling", "LogConflictError"):
            assert fragment in content, (path, fragment)
    guide = _read("docs/PREDICTIVE_EVALUATION.md")
    for fragment in ("historical snapshots", "FileExistsError", "without fitting again",
                     "aggregate numerical", "Failed", "never removed"):
        assert fragment.lower() in guide.lower()
