"""Release-assurance contracts introduced for the v3.0.1 preparation."""

from __future__ import annotations

import re
import tomllib
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
CONSTRAINT_FILES = (
    "constraints-py311-linux-x86_64.txt",
    "constraints-py312-linux-x86_64.txt",
    "constraints-py312-macos-arm64.txt",
    "constraints-py312-macos-x86_64.txt",
)


def _read(relative_path: str) -> str:
    return (PROJECT_ROOT / relative_path).read_text(encoding="utf-8")


def test_release_identity_and_maturity_are_aligned() -> None:
    pyproject = tomllib.loads(_read("pyproject.toml"))["project"]

    assert pyproject["version"] == "3.0.1"
    assert "Development Status :: 4 - Beta" in pyproject["classifiers"]
    assert "Development Status :: 5 - Production/Stable" not in pyproject["classifiers"]
    assert '__version__ = "3.0.1"' in _read("bo_forge/__init__.py")
    assert "# 🧪 BO Forge v3.0.1" in _read("README.md")
    assert "## v3.0.1 - CI-Backed Release Foundation" in _read("CHANGELOG.md")


def test_generated_constraints_are_hashed_and_resolver_pinned() -> None:
    requirements_dir = PROJECT_ROOT / "requirements"

    assert not (PROJECT_ROOT / "requirements-lock.txt").exists()
    generated = tuple(sorted(path.name for path in requirements_dir.glob("constraints-*.txt")))
    assert generated == CONSTRAINT_FILES
    for filename in CONSTRAINT_FILES:
        content = (requirements_dir / filename).read_text(encoding="utf-8")
        assert content.startswith("# This file was autogenerated by uv")
        assert "uv==0.11.3 pip compile pyproject.toml" in content.splitlines()[1]
        assert "--generate-hashes" in content.splitlines()[1]
        assert content.count("==") > 50
        assert content.count("--hash=sha256:") > 50

    for filename in CONSTRAINT_FILES[:2]:
        content = (requirements_dir / filename).read_text(encoding="utf-8")
        assert "--torch-backend cpu" in content.splitlines()[1]
        assert re.search(r"(?m)^torch==[^\s]+\+cpu \\\s*$", content)


def test_required_ci_covers_supported_platforms_and_artifacts() -> None:
    workflow = _read(".github/workflows/ci.yml")

    required_fragments = (
        "permissions:\n  contents: read",
        'python: "3.11"',
        'python: "3.12"',
        "runs-on: macos-14",
        "python -m pytest -p no:cacheprovider",
        "ruff check . --no-cache",
        "Verify generated constraints",
        "Path, lock, rollback, and mutation tests",
        "Bounded real numerical paths",
        "python -m build --outdir",
        "python -m twine check",
        "_assert_wheel_package_boundaries",
        "_assert_sdist_contains_release_assets",
        "python -m pip check",
        "bo-forge-app",
        "bo-forge-api",
        "from bo_forge_api.api import create_app",
    )
    for fragment in required_fragments:
        assert fragment in workflow

    assert "pull_request_target" not in workflow
    assert "from bo_forge_api import create_app" not in workflow
    assert "0.0.0.0" not in workflow
    assert workflow.count("timeout-minutes:") == 5


def test_future_tag_gate_validates_without_publishing() -> None:
    workflow = _read(".github/workflows/release-gate.yml")

    for fragment in (
        "tags: [\"v*\"]",
        "Tag {tag} does not match package version {version}",
        "Checked-out commit is not exactly tagged {tag}",
        "python -m pytest -p no:cacheprovider",
        "ruff check . --no-cache",
        "python -m build --outdir",
        "python -m twine check",
        "actions/upload-artifact@v4",
        "retention-days: 14",
    ):
        assert fragment in workflow

    forbidden = (
        "pull_request_target",
        "twine upload",
        "gh release",
        "pypa/gh-action-pypi-publish",
        "softprops/action-gh-release",
        "id-token: write",
    )
    for fragment in forbidden:
        assert fragment not in workflow


def test_release_facing_files_do_not_expose_author_home_paths() -> None:
    candidates = [
        PROJECT_ROOT / "README.md",
        PROJECT_ROOT / "CHANGELOG.md",
        PROJECT_ROOT / "CONTRIBUTING.md",
        PROJECT_ROOT / "SECURITY.md",
        PROJECT_ROOT / "MANIFEST.in",
        PROJECT_ROOT / "pyproject.toml",
        *PROJECT_ROOT.glob("ROADMAP*.md"),
        *PROJECT_ROOT.glob("docs/**/*.md"),
        *PROJECT_ROOT.glob("examples/**/*.py"),
        *PROJECT_ROOT.glob("notebooks/**/*.ipynb"),
    ]
    posix_home = re.compile(
        r"/(?:Users|home)/(?!USER(?:/|$)|user(?:/|$)|username(?:/|$)|"
        r"yourname(?:/|$)|<)[^/\s`\"']+/"
    )
    windows_home = re.compile(
        r"[A-Za-z]:\\Users\\(?!USER\\|user\\|username\\|yourname\\|<)"
        r"[^\\\s`\"']+\\"
    )

    offenders = []
    for path in candidates:
        content = path.read_text(encoding="utf-8")
        if posix_home.search(content) or windows_home.search(content):
            offenders.append(path.relative_to(PROJECT_ROOT).as_posix())

    assert offenders == []


def test_contribution_security_and_release_guidance_define_boundaries() -> None:
    contributing = _read("CONTRIBUTING.md")
    security = _read("SECURITY.md")
    release = _read("docs/RELEASE_CHECKLIST.md")

    assert "generated development constraints live in `requirements/`" in contributing
    assert "Do not hand-edit generated constraints" in contributing
    assert "private vulnerability reporting flow" in security.lower()
    assert "This file does not enable or" in security
    assert "verify that repository setting" in security
    assert "exact release commit is the authoritative gate" in release
    assert "Creating a tag, GitHub Release" in release
    assert "separate explicit authorization" in release


def test_v3_roadmap_records_assurance_and_future_findings() -> None:
    roadmap = _read("ROADMAP_V3_X.md")

    for node in ("v301", "v302", "v310", "v320", "v330", "v340", "v344"):
        assert f'{node}["' in roadmap
    for finding in ("REL-001", "REP-001", "REP-002", "DOC-001", "DOC-002", "DX-001"):
        assert finding in roadmap
    assert "Current prepared baseline: `v3.0.1`" in roadmap
    assert "Status: prepared; publication requires separate authorization" in roadmap
    assert "v3.0.2 - Conditional Post-Release Stabilization" in roadmap
    assert "No tag, GitHub Release, package publication, or push occurs" in roadmap
