"""Compatibility facade for campaign schema and validation helpers."""

from bo_forge._campaign.validation import (
    BASE_COLUMNS,
    COST_COLUMNS,
    REPLICATE_COLUMNS,
    RESULT_COLUMNS,
    REVIEW_COLUMNS,
    STAGE_COLUMNS,
    UTILITY_COLUMNS,
    VALID_MULTI_OBJECTIVE_SOURCES,
    VALID_REVIEW_STATUSES,
    VALID_SOURCES,
    VALID_STATUSES,
    canonical_columns,
    design_key_for_values,
    design_tuples,
    get_observed_data,
    has_blocking_qlog_nehvi_review_suggestions,
    has_blocking_qlog_nei_review_suggestions,
    has_pending_suggestions,
    next_iteration,
    qlog_nehvi_active_pending_suggestions,
    qlog_nei_active_pending_suggestions,
    validate_campaign_data,
)

__all__ = [
    "BASE_COLUMNS",
    "STAGE_COLUMNS",
    "REVIEW_COLUMNS",
    "REPLICATE_COLUMNS",
    "COST_COLUMNS",
    "RESULT_COLUMNS",
    "UTILITY_COLUMNS",
    "VALID_STATUSES",
    "VALID_SOURCES",
    "VALID_MULTI_OBJECTIVE_SOURCES",
    "VALID_REVIEW_STATUSES",
    "canonical_columns",
    "validate_campaign_data",
    "get_observed_data",
    "has_pending_suggestions",
    "has_blocking_qlog_nei_review_suggestions",
    "has_blocking_qlog_nehvi_review_suggestions",
    "qlog_nei_active_pending_suggestions",
    "qlog_nehvi_active_pending_suggestions",
    "design_tuples",
    "design_key_for_values",
    "next_iteration",
]
